=== hpepper/idea-to-product/sad2md/test/software_architecture_documentation.dtd
<!-- Version: 0.1.0 -->
<!-- validate xml: clear; xmllint -valid  itp.xml  > t 2>u; head u -->
<!-- the '-valid' actually has a double '-' in front but dtd can't have that. -->
<!ELEMENT SoftwareArchitectureDocumentation (
  Title,
  Issue,
  Revision,
  Draft,
  Status,
  ReleaseDate,
  Author,
  Summary,
  ViewPacket+,
  Component+,
  ComponentRelation*,
  Behavior*,
  Requirement*
)>
<!ATTLIST SoftwareArchitectureDocumentation Version CDATA #REQUIRED>

<!ELEMENT Author (#PCDATA)>
<!ELEMENT Draft (#PCDATA)>
<!ELEMENT Issue (#PCDATA)>
<!ELEMENT ReleaseDate (#PCDATA)>
<!ELEMENT Revision (#PCDATA)>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT Summary (#PCDATA)>
<!ELEMENT Title (#PCDATA)>

<!ELEMENT ViewPacket (
  Title?,
  ComponentRecurseLevel?,
  Introduction,
  ComponentId+,
  PrimaryDisplayKey,
  ContextModelKey?,
  DiagramKey*,
  ParentViewPacketId*,
  ChildViewPacketId*,
  SiblingViewPacketId*
)>
<!ATTLIST ViewPacket Id CDATA #REQUIRED>
<!ATTLIST ViewPacket ViewType  CDATA #REQUIRED>
<!ATTLIST ViewPacket ViewStyle  CDATA #REQUIRED>
<!ATTLIST ViewPacket SortOrder  CDATA #REQUIRED>

<!ELEMENT  ComponentRecurseLevel (#PCDATA)>
<!ELEMENT  DiagramKey (#PCDATA)>
<!ATTLIST  DiagramKey StyleType  CDATA #IMPLIED>
<!ELEMENT  Introduction (#PCDATA)>
<!ELEMENT  ComponentId (#PCDATA)>
<!ELEMENT  ContextModelKey (#PCDATA)>
<!ELEMENT  ParentViewPacketId (#PCDATA)>
<!ELEMENT  ChildViewPacketId (#PCDATA)>
<!ELEMENT  PrimaryDisplayKey (#PCDATA)>
<!ELEMENT  SiblingViewPacketId (#PCDATA)>

<!ELEMENT Behavior (
  ViewPacketId,
  Description,
  DiagramKey
)>
<!ATTLIST Behavior Id CDATA #REQUIRED>
<!ATTLIST Behavior SortOrder CDATA #REQUIRED>


<!ELEMENT  Description (#PCDATA)>
<!ELEMENT  ViewPacketId (#PCDATA)>


<!ELEMENT Component (
  ArtifactRepository*,
  ArchitectureDecisionId*,
  BehaviorDescription?,
  BuildCycle?,
  Capacity?,
  Contact*,
  File*,
  Functionality?,
  ImplementationConstraints?,
  Interface?,
  License*,
  Performance*,
  Reliability?,
  ResourceRequirement?,
  Purpose?,
  SchedulerPriority?,
  Security?,
  SourceRepository*,
  Summary,
  TestInformation?,
  VisibilityOfInterfaces?
)>
<!ATTLIST Component Id CDATA #REQUIRED>
<!ATTLIST Component Name CDATA #REQUIRED>

<!ELEMENT BehaviorDescription  (#PCDATA)>
<!ELEMENT Purpose  (#PCDATA)>
<!ELEMENT VisibilityOfInterfaces  (#PCDATA)>
<!ELEMENT Interface  (#PCDATA)>
<!ELEMENT Overview  (#PCDATA)>
<!ELEMENT BuildCycle  (#PCDATA)>
<!ELEMENT Contact  (#PCDATA)>
<!ELEMENT License  (#PCDATA)>
<!ELEMENT SourceRepository  (#PCDATA)>
<!ELEMENT ArtifactRepository  (#PCDATA)>
<!ELEMENT File  (#PCDATA)>
<!ELEMENT TestInformation  (#PCDATA)>
<!ELEMENT ImplementationConstraints  (#PCDATA)>
<!ELEMENT  Performance (#PCDATA)>
<!ELEMENT  Capacity (#PCDATA)>
<!ELEMENT  Reliability (#PCDATA)>
<!ELEMENT  ResourceRequirement (#PCDATA)>
<!ELEMENT  Functionality (#PCDATA)>
<!ELEMENT  Security (#PCDATA)>
<!ELEMENT  SchedulerPriority (#PCDATA)>
<!ELEMENT  ArchitectureDecisionId (#PCDATA)>

<!ELEMENT ComponentRelation (
  ComponentAId,
  ComponentBId,
  Key,
  PropertyOfRelation,
  ConnectionType?,
  RelationText?,
  RelationDescription?
)>
<!ATTLIST ComponentRelation Id CDATA #REQUIRED>
<!ATTLIST ComponentRelation SortOrder  CDATA #REQUIRED>

<!ELEMENT ComponentAId  (#PCDATA)>
<!ELEMENT ComponentBId  (#PCDATA)>
<!ELEMENT Key  (#PCDATA)>
<!ELEMENT PropertyOfRelation  (#PCDATA)>
<!ELEMENT ConnectionType  (#PCDATA)>
<!ELEMENT RelationText  (#PCDATA)>
<!ELEMENT RelationDescription  (#PCDATA)>

<!ELEMENT Diagram  (
  DiagramKey
)>

<!--See also: SwArcDocRequirements.md -->
<!ELEMENT Requirement (
  Priority?,
  Criticality?,
  Stability?,
  Feasibility?,
  Difficulty?,
  Risk?,
  Source?,
  Category?,
  PatternType?,
  ReqStatus?,
  Description?
)>
<!ATTLIST Requirement Identification CDATA #REQUIRED>
<!ATTLIST Requirement Title CDATA #REQUIRED>
<!ELEMENT Priority  (#PCDATA)>
<!ELEMENT Criticality  (#PCDATA)>
<!ELEMENT Stability  (#PCDATA)>
<!ELEMENT Feasibility  (#PCDATA)>
<!ELEMENT Difficulty  (#PCDATA)>
<!ELEMENT Risk  (#PCDATA)>
<!ELEMENT Source  (#PCDATA)>
<!ELEMENT Category  (#PCDATA)>
<!-- Category
  * Accessibility (e.g., different navigation paths for novice and experienced users);
  * Availability (e.g., expected hours of operation);
  * Compatibility to existing systems (e.g., uses analog telephone system as default mode);
  * Conversion (e.g., will accept data produced by older versions of system);
  * Documentation (e.g., on-line help facility);
  * Environmental conditions (e.g., dust levels that must be tolerated);
  * Ergonomic (e.g., use of particular colors to reduce eye strain);
  * External interfaces (e.g., support for industry standard communication mode/format);
  * Facility requirements (e.g., use of domestic electrical current);
  * Growth capacity (e.g., will support an additional number of users);
  * Input (e.g., receive EDI data);
  * Installation (e.g., ability to put a new system into service).
  * Maintainability (e.g., ease with which components can be replaced);
  * Output (e.g., export a particular format);
  * Performance (e.g., response time);
  * Policy and regulatory (e.g., environmental protection agency policies);
  * Quality provisions (e.g., minimum required calibration intervals);
  * Reliability (e.g., mean time to failure);
  * Safety (e.g., below specified limits for electrical magnetic radiation);
  * Security (e.g., limits to physical, functional, or data access, by authorized or unauthorized users);
  * Standards and technical policies (e.g., products to conform to ASME codes);
  * Testing (e.g., support for remote diagnostics);
  * Transportability (e.g., weight limits for portability);
  * Training (e.g., includes tutorials or computer-based training);  
  -->
<!ELEMENT PatternType  (#PCDATA)>
<!-- PatternType
  * Accessibility
  * Approval
  * Availability
  * Calculation Formula
  * Capacity, Dynamic
  * Capacity, Static
  * Chronicle
  * Comply-with-Standard
  * Configurable Authorization
  * Configuration
  * Data Archiving
  * Data Longevity
  * Data Structure
  * Data Type
  * Documentation
  * Extendability
  * ID
  * Information Storage Infrastructure
  * Inquiry
  * Installability
  * Inter-System Interface (e.g. )
  * Inter-System Interaction
  * Living Entity
  * Multi-Lingual
  * Multiness
  * Refer-to-Requirements
  * Report
  * Reporting Infrastructure
  * Response Time
  * Scalability
  * Specific Authorization
  * Technology
  * Throughput
  * Transaction
  * Unparochialness ' should this be Universalism?
  * Authentication, User
  * Authorizations, User
  * User Interface Infrastructure: A user interface infrastructure is a coherent set of components that together enable a user to interact with the system, excluding anything developed as part of a specific system, general underlying software (such as an operating system), and hardware(Wit07,163).
  * Registration, User
  -->
<!ELEMENT ReqStatus  (#PCDATA)>

=== hpepper/idea-to-product/sad2md/test/test_sad.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE SoftwareArchitectureDocumentation SYSTEM "software_architecture_documentation.dtd">

<SoftwareArchitectureDocumentation Version="0.1.1">
  <Title>SW Arcitechture Documentation for ITP"</Title>
  <Issue>0.1.0</Issue>
  <Revision>0.1.0</Revision>
  <Draft>1</Draft>
  <Status></Status>
  <ReleaseDate></ReleaseDate>
  <Author></Author>
  <Summary></Summary>

  <ViewPacket Id="1101" ViewType="Module" ViewStyle="Decomposition" SortOrder="1">
    <Title>Card game</Title>
    <Introduction>An online card battle game.</Introduction>
    <ComponentId>1</ComponentId>
    <PrimaryDisplayKey>Decomposition001</PrimaryDisplayKey>
    <ContextModelKey>ContextDiagram001</ContextModelKey>
  </ViewPacket>

  <ViewPacket Id="1102" ViewType="Module" ViewStyle="Decomposition" SortOrder="2">
    <Title>Game server</Title>
    <Introduction></Introduction>
    <ComponentId>3</ComponentId>
    <PrimaryDisplayKey>Decomposition002</PrimaryDisplayKey>
    <ContextModelKey></ContextModelKey>
  </ViewPacket>

  <ViewPacket Id="1103" ViewType="Module" ViewStyle="Decomposition" SortOrder="3">
    <Title>Edge connector</Title>
    <Introduction></Introduction>
    <ComponentId>7</ComponentId>
    <PrimaryDisplayKey>Decomposition003</PrimaryDisplayKey>
    <ContextModelKey></ContextModelKey>
  </ViewPacket>

  <ViewPacket Id="1106" ViewType="Module" ViewStyle="Decomposition" SortOrder="4">
    <Title>Message broker</Title>
    <Introduction></Introduction>
    <ComponentId>19</ComponentId>
    <PrimaryDisplayKey>Decomposition1106</PrimaryDisplayKey>
    <ContextModelKey></ContextModelKey>
  </ViewPacket>

  <ViewPacket Id="1202" ViewType="Module" ViewStyle="Uses" SortOrder="3">
    <Title>Edge connector</Title>
    <Introduction></Introduction>
    <ComponentId>7</ComponentId>
    <PrimaryDisplayKey>Uses1202</PrimaryDisplayKey>
    <ContextModelKey></ContextModelKey>
  </ViewPacket>
  <!-- TODO 
     What dependencies can be listed here?
     The contiainer is dependent on the OS being selected; rust vs javascript.
   -->

  <ViewPacket Id="1404" ViewType="Module" ViewStyle="Layered" SortOrder="1">
    <Title>Cloud presence layers</Title>
    <Introduction></Introduction>
    <ComponentId>18</ComponentId>
    <PrimaryDisplayKey>Layerd003</PrimaryDisplayKey>
    <ContextModelKey></ContextModelKey>
  </ViewPacket>

  <ViewPacket Id="14" ViewType="CnC" ViewStyle="ClientServer" SortOrder="1">
    <Title>EdgeConnector</Title>
    <Introduction></Introduction>
    <ComponentId>7</ComponentId>
    <PrimaryDisplayKey>ClientServer301</PrimaryDisplayKey>
    <ContextModelKey>ContextDiagram002</ContextModelKey>
  </ViewPacket>

  <Component Id="14" Name="BattleResolver">
    <Responsibilities></Responsibilities>
    <Summary>Execute the battle</Summary>
  </Component>
  <Component Id="15" Name="CardDeckStorage">
    <Responsibilities></Responsibilities>
    <Summary>Holds the current deck, plus any version of deck still being used in an ongoing session.</Summary>
  </Component>
  <Component Id="10" Name="Cloud provider">
    <Responsibilities></Responsibilities>
    <Summary></Summary>
  </Component>
  <Component Id="1" Name="Conflict card game">
    <Responsibilities></Responsibilities>
    <Summary>An online multiplayer tournament conflict card game.</Summary>
  </Component>
  <Component Id="7" Name="Edge connector">
    <Responsibilities></Responsibilities>
    <Summary>Receive client connections, validate the message and route the message.</Summary>
  </Component>
  <Component Id="5" Name="game download server">
    <Responsibilities></Responsibilities>
    <Summary>Hosts the download site for the game client application.</Summary>
  </Component>
  <Component Id="2" Name="Game client">
    <Responsibilities></Responsibilities>
    <Summary>Application running at the player end.</Summary>
  </Component>
  <Component Id="3" Name="Game server">
    <Responsibilities></Responsibilities>
    <Summary>The server side solution.</Summary>
  </Component>
  <Component Id="16" Name="Infrastructure">
    <Responsibilities></Responsibilities>
    <Summary></Summary>
  </Component>
  <Component Id="17" Name="kubernetes">
    <Responsibilities></Responsibilities>
    <Summary></Summary>
  </Component>
  <Component Id="8" Name="Message broker">
    <Responsibilities></Responsibilities>
    <Summary>Pub-sub server, enable transferring messages among server services.</Summary>
  </Component>
  <Component Id="19" Name="RabbitMQ Message broker">
    <Responsibilities></Responsibilities>
    <Summary>Pub-sub server, enable transferring messages among server services.</Summary>
    <!-- TODO describe why this RabbitMQ was chossen as the message broker. -->
  </Component>
  <Component Id="11" Name="oAuth">
    <Responsibilities></Responsibilities>
    <Summary>authorization that enables a user to grant an application access to their data on another application without sharing their credentials</Summary>
  </Component>
  <Component Id="6" Name="player statistics">
    <Responsibilities></Responsibilities>
    <Summary>API with access to all player statistics.</Summary>
  </Component>
  <Component Id="18" Name="Server applications">
    <Responsibilities></Responsibilities>
    <Summary></Summary>
  </Component>
  <Component Id="4" Name="server telemetry">
    <Responsibilities></Responsibilities>
    <Summary>Holds the the telemetry of all server side entities.</Summary>
  </Component>
  <Component Id="9" Name="Session manager">
    <Responsibilities></Responsibilities>
    <Summary>TODO Handle setting up game sessions, and transition the session between the different stations until the game is done.</Summary>
  </Component>
  <Component Id="13" Name="VillageSquare">
    <Responsibilities></Responsibilities>
    <Summary>Modify the deck for the next battle.</Summary>
  </Component>
  <Component Id="12" Name="Web browser">
    <Responsibilities></Responsibilities>
    <Summary>Web browser application.</Summary>
  </Component>


  <!-- 19
  <Component Id="" Name="">
    <Responsibilities></Responsibilities>
    <Summary></Summary>
  </Component>
  -->


  <ComponentRelation Id="1" SortOrder="">
    <ComponentAId>1</ComponentAId>
    <ComponentBId>2</ComponentBId>
    <Key>Decomposition001</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="2" SortOrder="">
    <ComponentAId>1</ComponentAId>
    <ComponentBId>3</ComponentBId>
    <Key>Decomposition001</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="3" SortOrder="">
    <ComponentAId>1</ComponentAId>
    <ComponentBId>4</ComponentBId>
    <Key>Decomposition001</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="4" SortOrder="">
    <ComponentAId>1</ComponentAId>
    <ComponentBId>5</ComponentBId>
    <Key>Decomposition001</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="5" SortOrder="">
    <ComponentAId>1</ComponentAId>
    <ComponentBId>6</ComponentBId>
    <Key>Decomposition001</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="6" SortOrder="">
    <ComponentAId>3</ComponentAId>
    <ComponentBId>7</ComponentBId>
    <Key>Decomposition002</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="7" SortOrder="">
    <ComponentAId>3</ComponentAId>
    <ComponentBId>8</ComponentBId>
    <Key>Decomposition002</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="8" SortOrder="">
    <ComponentAId>3</ComponentAId>
    <ComponentBId>9</ComponentBId>
    <Key>Decomposition002</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="15" SortOrder="">
    <ComponentAId>3</ComponentAId>
    <ComponentBId>13</ComponentBId>
    <Key>Decomposition002</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>
  <ComponentRelation Id="16" SortOrder="">
    <ComponentAId>3</ComponentAId>
    <ComponentBId>14</ComponentBId>
    <Key>Decomposition002</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>
  <ComponentRelation Id="17" SortOrder="">
    <ComponentAId>3</ComponentAId>
    <ComponentBId>15</ComponentBId>
    <Key>Decomposition002</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>


  <ComponentRelation Id="9" SortOrder="">
    <ComponentAId>1</ComponentAId>
    <ComponentBId>10</ComponentBId>
    <Key>ContextDiagram001</Key>
    <PropertyOfRelation></PropertyOfRelation>
    <RelationText>IaaS</RelationText>
    <RelationDescription>Iaas operations</RelationDescription>
  </ComponentRelation>

  <!-- The ComponentAId is 'The Work' in a context diagram. -->
  <ComponentRelation Id="10" SortOrder="">
    <ComponentAId>1</ComponentAId>
    <ComponentBId>11</ComponentBId>
    <Key>ContextDiagram001</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="11" SortOrder="">
    <ComponentAId>1</ComponentAId>
    <ComponentBId>12</ComponentBId>
    <Key>ContextDiagram001</Key>
    <PropertyOfRelation></PropertyOfRelation>
  </ComponentRelation>

  <ComponentRelation Id="12" SortOrder="">
    <ComponentAId>2</ComponentAId>
    <ComponentBId>7</ComponentBId>
    <Key>ClientServer301</Key>
    <PropertyOfRelation></PropertyOfRelation>
    <RelationText>Web Socket</RelationText>
    <RelationDescription>Web Socket stream</RelationDescription>
  </ComponentRelation>

  <ComponentRelation Id="13" SortOrder="">
    <ComponentAId>7</ComponentAId>
    <ComponentBId>8</ComponentBId>
    <Key>ClientServer301</Key>
    <PropertyOfRelation></PropertyOfRelation>
    <RelationText>RabbitMQ msg</RelationText>
  </ComponentRelation>

  <ComponentRelation Id="14" SortOrder="">
