=== hpepper/idea-to-product/sad_xml_sql/tests/software_architecture_documentation.dtd
<!-- Version: 0.1.0 -->
<!-- validate xml: clear; xmllint -valid  itp.xml  > t 2>u; head u -->
<!-- the '-valid' actually has a double '-' in front but dtd can't have that. -->
<!ELEMENT SoftwareArchitectureDocumentation (
  Document,
  Include*,
  ViewPacket+,
  Component+,
  ComponentRelation*,
  Behavior*,
  Requirement*,
  Team*
)>
<!ATTLIST SoftwareArchitectureDocumentation Version CDATA #REQUIRED>

<!ELEMENT Document (
  FileId,
  Title,
  Issue,
  Summary
)>

<!ELEMENT FileId (#PCDATA)>
<!ELEMENT Include (#PCDATA)>
<!ATTLIST Include url CDATA #REQUIRED>
<!ELEMENT Issue (#PCDATA)>
<!ELEMENT Summary (#PCDATA)>
<!ELEMENT Title (#PCDATA)>

<!ELEMENT ViewPacket (
  Title?,
  ComponentRecurseLevel?,
  Introduction,
  ComponentId+,
  PrimaryDisplayKey,
  ContextModelKey?,
  DiagramKey*,
  ParentViewPacketId*,
  ChildViewPacketId*,
  SiblingViewPacketId*,
  TeamId?
)>
<!ATTLIST ViewPacket Id CDATA #REQUIRED>
<!ATTLIST ViewPacket ViewType  CDATA #REQUIRED>
<!ATTLIST ViewPacket ViewStyle  CDATA #REQUIRED>
<!ATTLIST ViewPacket SortOrder  CDATA #REQUIRED>

<!ELEMENT  ComponentRecurseLevel (#PCDATA)>
<!ELEMENT  DiagramKey (#PCDATA)>
<!ATTLIST  DiagramKey StyleType  CDATA #IMPLIED>
<!ELEMENT  Introduction (#PCDATA)>
<!ELEMENT  ComponentId (#PCDATA)>
<!ELEMENT  ContextModelKey (#PCDATA)>
<!ELEMENT  ParentViewPacketId (#PCDATA)>
<!ELEMENT  ChildViewPacketId (#PCDATA)>
<!ELEMENT  PrimaryDisplayKey (#PCDATA)>
<!ELEMENT  SiblingViewPacketId (#PCDATA)>
<!ELEMENT  TeamId (#PCDATA)>

<!ELEMENT Behavior (
  ViewPacketId,
  Description,
  DiagramKey
)>
<!ATTLIST Behavior Id CDATA #REQUIRED>
<!ATTLIST Behavior SortOrder CDATA #REQUIRED>


<!ELEMENT  Description (#PCDATA)>
<!ELEMENT  ViewPacketId (#PCDATA)>


<!ELEMENT Component (
  ArtifactRepository*,
  ArchitectureDecisionId*,
  BehaviorDescription?,
  BuildCycle?,
  Capacity?,
  Contact*,
  File*,
  Functionality?,
  ImplementationConstraints?,
  Interface?,
  License*,
  Performance*,
  Reliability?,
  ResourceRequirement?,
  Purpose?,
  SchedulerPriority?,
  Security?,
  SourceRepository*,
  Summary,
  TeamId?,
  TestInformation?,
  Title?,
  VisibilityOfInterfaces?
)>
<!ATTLIST Component Id CDATA #REQUIRED>
<!ATTLIST Component Name CDATA #REQUIRED>

<!ELEMENT BehaviorDescription  (#PCDATA)>
<!ELEMENT Purpose  (#PCDATA)>
<!ELEMENT VisibilityOfInterfaces  (#PCDATA)>
<!ELEMENT Interface  (#PCDATA)>
<!ELEMENT Overview  (#PCDATA)>
<!ELEMENT BuildCycle  (#PCDATA)>
<!ELEMENT Contact  (#PCDATA)>
<!ELEMENT License  (#PCDATA)>
<!ELEMENT SourceRepository  (#PCDATA)>
<!ELEMENT ArtifactRepository  (#PCDATA)>
<!ELEMENT File  (#PCDATA)>
<!ELEMENT TestInformation  (#PCDATA)>
<!ELEMENT ImplementationConstraints  (#PCDATA)>
<!ELEMENT  Performance (#PCDATA)>
<!ELEMENT  Capacity (#PCDATA)>
<!ELEMENT  Reliability (#PCDATA)>
<!ELEMENT  ResourceRequirement (#PCDATA)>
<!ELEMENT  Functionality (#PCDATA)>
<!ELEMENT  Security (#PCDATA)>
<!ELEMENT  SchedulerPriority (#PCDATA)>
<!ELEMENT  ArchitectureDecisionId (#PCDATA)>

<!ELEMENT ComponentRelation (
  ComponentAId,
  ComponentBId,
  Key,
  PropertyOfRelation,
  ConnectionType?,
  RelationText?,
  RelationDescription?,
  Style?
)>
<!ATTLIST ComponentRelation Id CDATA #REQUIRED>
<!ATTLIST ComponentRelation SortOrder  CDATA #REQUIRED>

<!ELEMENT ComponentAId  (#PCDATA)>
<!ELEMENT ComponentBId  (#PCDATA)>
<!ELEMENT Style  (#PCDATA)>
<!ELEMENT ConnectionType  (#PCDATA)>
<!ELEMENT Key  (#PCDATA)>
<!ELEMENT PropertyOfRelation  (#PCDATA)>
<!ELEMENT RelationText  (#PCDATA)>
<!ELEMENT RelationDescription  (#PCDATA)>

<!ELEMENT Diagram  (
  DiagramKey
)>

<!--See also: SwArcDocRequirements.md -->
<!ELEMENT Requirement (
  Priority?,
  Criticality?,
  Stability?,
  Feasibility?,
  Difficulty?,
  Risk?,
  Source?,
  Category?,
  PatternType?,
  ReqStatus?,
  Description?
)>
<!ATTLIST Requirement Identification CDATA #REQUIRED>
<!ATTLIST Requirement Title CDATA #REQUIRED>
<!ELEMENT Priority  (#PCDATA)>
<!ELEMENT Criticality  (#PCDATA)>
<!ELEMENT Stability  (#PCDATA)>
<!ELEMENT Feasibility  (#PCDATA)>
<!ELEMENT Difficulty  (#PCDATA)>
<!ELEMENT Risk  (#PCDATA)>
<!ELEMENT Source  (#PCDATA)>
<!ELEMENT Category  (#PCDATA)>
<!-- Category
  * Accessibility (e.g., different navigation paths for novice and experienced users);
  * Availability (e.g., expected hours of operation);
  * Compatibility to existing systems (e.g., uses analog telephone system as default mode);
  * Conversion (e.g., will accept data produced by older versions of system);
  * Documentation (e.g., on-line help facility);
  * Environmental conditions (e.g., dust levels that must be tolerated);
  * Ergonomic (e.g., use of particular colors to reduce eye strain);
  * External interfaces (e.g., support for industry standard communication mode/format);
  * Facility requirements (e.g., use of domestic electrical current);
  * Growth capacity (e.g., will support an additional number of users);
  * Input (e.g., receive EDI data);
  * Installation (e.g., ability to put a new system into service).
  * Maintainability (e.g., ease with which components can be replaced);
  * Output (e.g., export a particular format);
  * Performance (e.g., response time);
  * Policy and regulatory (e.g., environmental protection agency policies);
  * Quality provisions (e.g., minimum required calibration intervals);
  * Reliability (e.g., mean time to failure);
  * Safety (e.g., below specified limits for electrical magnetic radiation);
  * Security (e.g., limits to physical, functional, or data access, by authorized or unauthorized users);
  * Standards and technical policies (e.g., products to conform to ASME codes);
  * Testing (e.g., support for remote diagnostics);
  * Transportability (e.g., weight limits for portability);
  * Training (e.g., includes tutorials or computer-based training);  
  -->
<!ELEMENT PatternType  (#PCDATA)>
<!-- PatternType
  * Accessibility
  * Approval
  * Availability
  * Calculation Formula
  * Capacity, Dynamic
  * Capacity, Static
  * Chronicle
  * Comply-with-Standard
  * Configurable Authorization
  * Configuration
  * Data Archiving
  * Data Longevity
  * Data Structure
  * Data Type
  * Documentation
  * Extendability
  * ID
  * Information Storage Infrastructure
  * Inquiry
  * Installability
  * Inter-System Interface (e.g. )
  * Inter-System Interaction
  * Living Entity
  * Multi-Lingual
  * Multiness
  * Refer-to-Requirements
  * Report
  * Reporting Infrastructure
  * Response Time
  * Scalability
  * Specific Authorization
  * Technology
  * Throughput
  * Transaction
  * Unparochialness ' should this be Universalism?
  * Authentication, User
  * Authorizations, User
  * User Interface Infrastructure: A user interface infrastructure is a coherent set of components that together enable a user to interact with the system, excluding anything developed as part of a specific system, general underlying software (such as an operating system), and hardware(Wit07,163).
  * Registration, User
  -->
<!ELEMENT ReqStatus  (#PCDATA)>

<!ELEMENT Team  (
  Description?,
  Member*
)>
<!ATTLIST Team Id CDATA #REQUIRED>
<!ATTLIST Team Name CDATA #REQUIRED>

<!ELEMENT Member  (#PCDATA)>
<!ATTLIST Member Role CDATA #REQUIRED>

=== hpepper/idea-to-product/sad_xml_sql/tests/test_infrastructure_sad.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE SoftwareArchitectureDocumentation SYSTEM "software_architecture_documentation.dtd">

<SoftwareArchitectureDocumentation Version="0.1.1">
  <Document>
    <FileId>2</FileId>
    <Title>example of Infrastructure Architecture Documentation</Title>
    <Issue>0.1.0</Issue>
    <Summary>provide an example of Software Architecture Document</Summary>
  </Document>

  <ViewPacket Id="2.1.1.1" ViewType="Module" ViewStyle="Decomposition" SortOrder="1">
    <Title>Application infrastructure</Title>
    <Introduction>The application infrastructure</Introduction>
    <ComponentId>2.0.0.1</ComponentId>
    <PrimaryDisplayKey>Decomposition-1.1.1</PrimaryDisplayKey>
    <ContextModelKey>ContextDiagram001</ContextModelKey>
  </ViewPacket>

  <ViewPacket Id="2.1.1.2" ViewType="Module" ViewStyle="Decomposition" SortOrder="2">
    <Title>Kubernetes infrastructure</Title>
    <Introduction>The Kubernetes infrastructure</Introduction>
    <ComponentId>2.0.0.2</ComponentId>
    <PrimaryDisplayKey>DecompositionKubernetes</PrimaryDisplayKey>
    <ContextModelKey>ContextDiagramKubernetes</ContextModelKey>
  </ViewPacket>

  <Component Id="2.0.0.1" Name="Infrastructure">
    <Purpose></Purpose>
    <Summary>Provide the infrastructure for the application</Summary>
  </Component>
  <Component Id="2.0.0.2" Name="Kubernetes Cluster">
    <Purpose></Purpose>
    <Summary>Container orchestration platform.</Summary>
  </Component>

  <ComponentRelation Id="2.0.1.1" SortOrder="">
    <ComponentAId>2.0.0.1</ComponentAId>
    <ComponentBId>2.0.0.2</ComponentBId>
    <Key>Decomposition-1.1.1</Key>
    <PropertyOfRelation></PropertyOfRelation>
    <RelationText></RelationText>
    <RelationDescription></RelationDescription>
    <Style></Style>
  </ComponentRelation>

  <!-- 36
  <ComponentRelation Id="" SortOrder="">
    <ComponentAId></ComponentAId>
    <ComponentBId></ComponentBId>
    <Key></Key>
    <PropertyOfRelation></PropertyOfRelation>
    <RelationText></RelationText>
    <RelationDescription></RelationDescription>
    <Style></Style>
  </ComponentRelation>
  -->


</SoftwareArchitectureDocumentation>
